name: build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2019
    steps:
    - uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          git
          base-devel zip

    - uses: actions/checkout@v2
    - run: |
        git config --global user.email "yaofei365@126.com"
        git config --global user.name "yaofei365"
 
    - name: Make
      run: |
        make

    - name: Build
      shell: msys2 {0}
      run: |
        zip -j Lua.zip lua/src/lua.exe

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.ACTIONS_REMOTE_BUILD_TOKEN }}
        file: Lua.zip
        asset_name: Lua.zip
        tag: ${{ github.ref }}
        overwrite: true
        body: "Lua.exe"
